server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_security?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

token:
  jwtSecret: zhoulihuang
  expire:
    seconds: 3600

